name: zoonotic_rank

channels:
  - conda-forge

dependencies:
  - r-base=3.5.1
  - r-argparse=2.0.1
  - r-rprojroot=1.3_2
  - r-seqinr=3.4
  - r-dplyr=0.8.3
  - r-tidyr=0.8.3
  - r-stringr=1.4.0
  - r-readr=1.3.1
  - r-ggplot2=3.2.0
  - r-xgboost=0.90
  - r-caret=6.0_85
  - r-modelmetrics=1.2
  - r-apcluster=1.4.8
  - r-ape=5.1
  - r-envstats=2.3.1
  - python=3.6.5
  - biopython=1.72
  - xlrd=1.1.0
  - pandas=0.23.0
  - requests=2.18.4
  - openjdk=11.0.1
